version: '3.8'
services:
  workout_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
      #.:/app allows changes from app to be passed to docker file app and vice versa.