# Generated by Django 3.1.4 on 2021-01-13 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0003_auto_20210107_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('set_amount', models.IntegerField()),
                ('total_reps', models.IntegerField()),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('exercise_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exercises.exercises')),
            ],
        ),
    ]
