# Generated by Django 3.1.4 on 2021-03-04 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisesdetails', '0002_auto_20210113_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesdetails',
            name='weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
    ]
