# Generated by Django 3.1.4 on 2021-03-04 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisesdetails', '0003_auto_20210304_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesdetails',
            name='set_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='exercisesdetails',
            name='total_reps',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
