# Generated by Django 3.1.4 on 2021-01-08 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210103_0417'),
        ('exercises', '0002_auto_20210103_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='username',
        ),
        migrations.AddField(
            model_name='exercises',
            name='workout_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workouts.workouts'),
        ),
    ]
