# Generated by Django 3.1.4 on 2021-01-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20210107_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='totalVolume',
            field=models.IntegerField(default=0),
        ),
    ]
