# Generated by Django 3.1.4 on 2021-01-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='date',
            field=models.DateField(),
        ),
    ]
